<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
	/**
	* Run the database seeds.
	*/
	public function run(): void
	{
		Product::insert([
			[
				"product_name" => "Axis 10.000",
				"category" => "Pulsa",
				"brand" => "AXIS",
				"type" => "Umum",
				"seller_name" => "PT***",
				"price" => 10890,
				"buyer_sku_code" => "ax10",
				"buyer_product_status" => true,
				"seller_product_status" => true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" => "0:1",
				"description" => "Reguler"
			],
			[
				"product_name" => "Axis 5.000",
				"category" => "Pulsa",
				"brand" => "AXIS",
				"type" => "Umum",
				"seller_name" => "PT***",
				"price" => 5770,
				"buyer_sku_code" => "ax5",
				"buyer_product_status" => true,
				"seller_product_status" => true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" => "0:1",
				"description" => "Reguler"
			],
			[
				"product_name" => "Axis Data Jawa 2.5 GB 5 Hari",
				"category" => "Data",
				"brand" => "AXIS",
				"type" => "Jawa Bali Nusra",
				"seller_name" => "Om***",
				"price" => 11992,
				"buyer_sku_code" => "axdj1",
				"buyer_product_status" => true,
				"seller_product_status" => true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" => "0:15",
				"description" => "AIGO Mini 2.5GB + Lokal Jawa Bali Nusra 5hr"
			],
			[
				"product_name" => "Axis Data SS 2 GB 3 Hari",
				"category" => "Data",
				"brand" => "AXIS",
				"type" => "Aigo SS",
				"seller_name" => "PT***",
				"price" => 8605,
				"buyer_sku_code" => "axdss2",
				"buyer_product_status" => true,
				"seller_product_status" => true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" => "0:30",
				"description" => "Axis Data SS AIGO Mini Bronet 24Jam 2GB + Kuota di Kota-mu 3hr"
			],
			[
				"product_name" => "Aktivasi Perdana Axis 3 GB 60 Hari (SP5K SP7K)",
				"category" => "Aktivasi Perdana",
				"brand" => "AXIS",
				"type" => "SP5K SP7K",
				"seller_name" => "ma***",
				"price" => 13905,
				"buyer_sku_code" => "axp3g60d",
				"buyer_product_status" => true,
				"seller_product_status" => true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:55",
				"end_cut_off" => "0:5",
				"description" => "Perdana Bronet 3GB + Kuota di Kota-mu 60hr"
			],
			[
				"product_name" => "by.U 10.000",
				"category" => "Pulsa",
				"brand" => "by.U",
				"type" => "Umum",
				"seller_name" => "Zo***",
				"price" => 10250,
				"buyer_sku_code" => "byu10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" => "0:30",
				"description" => "Reguler"
			],
			[
				"product_name" => "DANA 20.000",
				"category" => "E-Money",
				"brand" => "DANA",
				"type" => "Umum",
				"seller_name" => "BC***",
				"price" => 20135,
				"buyer_sku_code" => "dana20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" => "0:15",
				"description" => "-"
			],
			[
				"product_name" => "DANA 50.000",
				"category" => "E-Money",
				"brand" => "DANA",
				"type" => "Umum",
				"seller_name" => "BC***",
				"price" => 50150,
				"buyer_sku_code" => "dana50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "-"
			],
			[
				"product_name" => "Cek Nama Pengguna DANA",
				"category" => "E-Money",
				"brand" => "DANA",
				"type" => "Umum",
				"seller_name" => "ZP***",
				"price" => 5,
				"buyer_sku_code" => "danacek",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" => "0:1",
				"description" => "-"
			],
			[
				"product_name" => "Free Fire 12 Diamond",
				"category" => "Games",
				"brand" => "FREE FIRE",
				"type" => "Umum",
				"seller_name" => "Di***",
				"price" => 1687,
				"buyer_sku_code" => "ff12",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" => "0:0",
				"description" => "Jumlah diamond sesuai diamond normal, bonus tidak dihitung"
			],
			[
				"product_name" => "Free Fire 140 Diamond",
				"category" => "Games",
				"brand" => "FREE FIRE",
				"type" => "Umum",
				"seller_name" => "Sq***",
				"price" => 17868,
				"buyer_sku_code" => "ff140",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Jumlah diamond sesuai diamond normal, bonus tidak dihitung"
			],
			[
				"product_name" => "Free Fire 355 Diamond",
				"category" => "Games",
				"brand" => "FREE FIRE",
				"type" => "Umum",
				"seller_name" => "Mi***",
				"price" => 43575,
				"buyer_sku_code" => "ff355",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" =>true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Jumlah diamond sesuai diamond normal, bonus tidak dihitung"
			],
			[
				"product_name" => "Free Fire 50 Diamond",
				"category" => "Games",
				"brand" => "FREE FIRE",
				"type" => "Umum",
				"seller_name" => "BO***",
				"price" => 6234,
				"buyer_sku_code" => "ff50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Jumlah diamond sesuai diamond normal, bonus tidak dihitung"
			],
			[
				"product_name" => "Free Fire 70 Diamond",
				"category" => "Games",
				"brand" => "FREE FIRE",
				"type" => "Umum",
				"seller_name" => "De***",
				"price" => 9305,
				"buyer_sku_code" => "ff70",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" =>"0:1",
				"description" => "Jumlah diamond sesuai diamond normal, bonus tidak dihitung"
			],
			[
				"product_name" => "Telkomsel Data Flash 1 GB 30 Hari",
				"category" => "Data",
				"brand" => "TELKOMSEL",
				"type" => "Flash",
				"seller_name" => "Ko***",
				"price" => 12360,
				"buyer_sku_code" => "flash1",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:0",
				"end_cut_off" => "1:0",
				"description" => "24 jam nasional."
			],
			[
				"product_name" => "Telkomsel Data Flash 2 GB 30 Hari",
				"category" => "Data",
				"brand" => "TELKOMSEL",
				"type" => "Flash",
				"seller_name" => "KI***",
				"price" => 22093,
				"buyer_sku_code" => "flash2",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "24 jam nasional."
			],
			[
				"product_name" => "Telkomsel Data Flash 3 GB 30 Hari",
				"category" => "Data",
				"brand" => "TELKOMSEL",
				"type" => "Flash",
				"seller_name" => "PT***",
				"price" => 19975,
				"buyer_sku_code" => "flash3",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "24 jam nasional."
			],
			[
				"product_name" => "XL Xtra Combo Flex S 28 Hari",
				"category" => "Data",
				"brand" => "XL",
				"type" => "Xtra Combo Flex",
				"seller_name" => "PT***",
				"price" => 25985,
				"buyer_sku_code" => "flexs",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" =>"0:1",
				"description" => "Xtra Combo Flex S"
			],
			[
				"product_name" => "Go Pay 100.000",
				"category" => "E-Money",
				"brand" => "GO PAY",
				"type" => "Customer",
				"seller_name" => "PT***",
				"price" => 100650,
				"buyer_sku_code" => "go100",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Masukan no HP"
			],
			[
				"product_name" => "Go Pay 50.000",
				"category" => "E-Money",
				"brand" => "GO PAY",
				"type" => "Customer",
				"seller_name" => "BC***",
				"price" => 50650,
				"buyer_sku_code" => "go50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "Masukan no HP"
			],
			[
				"product_name" => "Cek Nama Pengguna Gopay",
				"category" => "E-Money",
				"brand" => "GO PAY",
				"type" => "Umum",
				"seller_name" => "Gi***",
				"price" => 10,
				"buyer_sku_code" => "gopaycek",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "-"
			],
			[
				"product_name" => "Tri Data Happy 1.5 GB 1 Hari",
				"category" => "Data",
				"brand" => "TRI",
				"type" => "Happy",
				"seller_name" => "MU***",
				"price" => 5340,
				"buyer_sku_code" => "happy1",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "Tri Data Happy 1.5 GB / 1 Hari"
			],
			[
				"product_name" => "Tri Data Happy 3 GB 3 Hari",
				"category" => "Data",
				"brand" => "TRI",
				"type" => "Happy",
				"seller_name" => "BU***",
				"price" => 10420,
				"buyer_sku_code" => "happy3",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" =>"23:45",
				"end_cut_off" =>"0:15",
				"description" => "Tri Data Happy 3 GB / 3 Hari"
			],
			[
				"product_name" => "Aktivasi Voucher XL XTRA HotRod Special 3 GB 10 Hari",
				"category" => "Aktivasi Voucher",
				"brand" => "XL",
				"type" => "Hotrod Special",
				"seller_name" => "Ki***",
				"price" => 17100,
				"buyer_sku_code" => "hotrod3g10d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => false,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Aktivasi Voucher Xtra Hotrod Special 3GB,10hr"
			],
			[
				"product_name" => "Indosat 10.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "AL***",
				"price" => 12455,
				"buyer_sku_code" => "i10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:5",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat 20.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "Me***",
				"price" => 20887,
				"buyer_sku_code" => "i20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" => 0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat 25.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "DY***",
				"price" => 25631,
				"buyer_sku_code" => "i25",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" =>"23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat 30.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "Na***",
				"price" => 30255,
				"buyer_sku_code" => "i30",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat 5.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "Mi***",
				"price" => 6635,
				"buyer_sku_code" => "i5",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat 50.000",
				"category" => "Pulsa",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "Mi***",
				"price" => 48825,
				"buyer_sku_code" => "i50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat Tambah Masa Aktif Kartu 90 Hari",
				"category" => "Masa Aktif",
				"brand" => "INDOSAT",
				"type" => "Umum",
				"seller_name" => "op***",
				"price" => 13860,
				"buyer_sku_code" => "iactive90",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "-"
			],
			[
				"product_name" => "Indosat Freedom Internet 2.5 GB 5 Hari",
				"category" => "Data",
				"brand" => "INDOSAT",
				"type" => "Freedom Internet",
				"seller_name" => "BU***",
				"price" => 12750,
				"buyer_sku_code" => "if2",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Freedom Internet 2.5GB/5hr"
			],
			[
				"product_name" => "Indosat Freedom Internet 3 GB 28 Hari",
				"category" => "Data",
				"brand" => "INDOSAT",
				"type" => "Freedom Internet",
				"seller_name" => "PT***",
				"price" => 21060,
				"buyer_sku_code" => "if3g30d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Freedom Internet 3GB/28 Hari"
			],
			[
				"product_name" => "Indosat Freedom Internet 3 GB 3 Hari",
				"category" => "Data",
				"brand" => "INDOSAT",
				"type" => "Freedom Internet",
				"seller_name" => "MU***",
				"price" => 11505,
				"buyer_sku_code" => "if3g3d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "Freedom Internet 3GB/3hr"
			],
			[
				"product_name" => "Indosat Freedom Internet 5.5 GB 28 Hari",
				"category" => "Data",
				"brand" => "INDOSAT",
				"type" => "Freedom Internet",
				"seller_name" => "BU***",
				"price" => 29025,
				"buyer_sku_code" => "if5g30d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Freedom Internet 5.5GB/28 Hari"
			],
			[
				"product_name" => "K-Vision & GOL Paket CLING (CL06)  180 Hari",
				"category" => "TV",
				"brand" => "K-VISION dan GOL",
				"type" => "Cling",
				"seller_name" => "SM***",
				"price" => 75990,
				"buyer_sku_code" => "kvision180d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Siaran National Geographic, Nat Geo Wild, My Family, My Cinema, MTV, Rock , Kids TV, dll"
			],
			[
				"product_name" => "K-Vision & GOL Paket CLING (CL01)  30 Hari",
				"category" => "TV",
				"brand" => "K-VISION dan GOL",
				"type" => "Cling",
				"seller_name" => "CV***",
				"price" => 19460,
				"buyer_sku_code" => "kvision30d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:15",
				"description" => "Siaran National Geographic, Nat Geo Wild, My Family, My Cinema, MTV, Rock , Kids TV, dll"
			],
			[
				"product_name" => "MOBILELEGEND - 10 Diamond",
				"category" => "Games",
				"brand" => "MOBILE LEGENDS",
				"type" => "Umum",
				"seller_name" => "BO***",
				"price" => 2854,
				"buyer_sku_code" => "ml10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "no pelanggan = gabungan antara user_id dan zone_id"
			],
			[
				"product_name" => "MOBILELEGEND - 12 Diamond",
				"category" => "Games",
				"brand" => "MOBILE LEGENDS",
				"type" => "Umum",
				"seller_name" => "KA***",
				"price" => 3297,
				"buyer_sku_code" => "ml12",
				"buyer_product_status" => true,
				"seller_product_status" =>false,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "no pelanggan = gabungan antara user_id dan zone_id"
			],
			[
				"product_name" => "MOBILELEGEND - 5 Diamond",
				"category" => "Games",
				"brand" => "MOBILE LEGENDS",
				"type" => "Umum",
				"seller_name" => "Mi***",
				"price" => 1475,
				"buyer_sku_code" => "ml5",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "no pelanggan = gabungan antara user_id dan zone_id"
			],
			[
				"product_name" => "MOBILE LEGENDS Weekly Diamond Pass",
				"category" => "Games",
				"brand" => "MOBILE LEGENDS",
				"type" => "Membership",
				"seller_name" => "BC***",
				"price" => 27997,
				"buyer_sku_code" => "mlweek",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "-"
			],
			[
				"product_name" => "OVO 100.000",
				"category" => "E-Money",
				"brand" => "OVO",
				"type" => "Umum",
				"seller_name" => "SM***",
				"price" => 100749,
				"buyer_sku_code" => "ovo100",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:50",
				"end_cut_off" =>"0:15",
				"description" => "OVO 100.000"
			],
			[
				"product_name" => "OVO 50.000",
				"category" => "E-Money",
				"brand" => "OVO",
				"type" => "Umum",
				"seller_name" => "ZP***",
				"price" => 50675,
				"buyer_sku_code" => "ovo50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "OVO 50.000"
			],
			[
				"product_name" => "Cek Nama Pengguna OVO",
				"category" => "E-Money",
				"brand" => "OVO",
				"type" => "Umum",
				"seller_name" => "Gi***",
				"price" => 10,
				"buyer_sku_code" => "ovocek",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "-"
			],
			[
				"product_name" => "Telkomsel Telepon Pas 10.000",
				"category" => "Paket SMS & Telpon",
				"brand" => "TELKOMSEL",
				"type" => "Telepon Pas",
				"seller_name" => "BC***",
				"price" => 10660,
				"buyer_sku_code" => "pas10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" =>"23:30",
				"end_cut_off" =>"0:15",
				"description" => "Telepon 170 menit sesama, 30 menit semua op 3 Hari (sesuai zona)"
			],
			[
				"product_name" => "Telkomsel Telepon Pas 20.000",
				"category" => "Paket SMS & Telpon",
				"brand" => "TELKOMSEL",
				"type" => "Telepon Pas",
				"seller_name" => "Qu***",
				"price" => 17010,
				"buyer_sku_code" => "pas20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" =>"23:45",
				"end_cut_off" =>"0:15",
				"description" => "Telepon 300 menit semua op 7 Hari (sesuai zona)"
			],
			[
				"product_name" => "Telkomsel Telepon Pas 50.000",
				"category" => "Paket SMS & Telpon",
				"brand" => "TELKOMSEL",
				"type" => "Telepon Pas",
				"seller_name" => "NE***",
				"price" => 21330,
				"buyer_sku_code" => "pas50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" =>"23:45",
				"end_cut_off" =>"0:15",
				"description" => "Telepon 1000 menit sesama, 100 menit semua op (30 Hari) (manfaat sesuai zona)"
			],
			[
				"product_name" => "Pertagas 20.000",
				"category" => "Gas",
				"brand" => "Pertamina Gas",
				"type" => "Umum",
				"seller_name" => "MU***",
				"price" => 21510,
				"buyer_sku_code" => "pertagas20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "Pertagas 20.000"
			],
			[
				"product_name" => "PLN 100.000",
				"category" => "PLN",
				"brand" => "PLN",
				"type" => "Umum",
				"seller_name" => "MU***",
				"price" => 100565,
				"buyer_sku_code" => "pln100",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "masukkan nomor meter/id pelanggan"
			],
			[
				"product_name" => "PLN 1.000.000",
				"category" => "PLN",
				"brand" => "PLN",
				"type" => "Umum",
				"seller_name" => "Am***",
				"price" => 998000,
				"buyer_sku_code" => "pln1000",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "masukkan nomor meter/id pelanggan"
			],
			[
				"product_name" => "PLN 20.000",
				"category" => "PLN",
				"brand" => "PLN",
				"type" => "Umum",
				"seller_name" => "BC***",
				"price" => 21759,
				"buyer_sku_code" => "pln20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "masukkan nomor meter/id pelanggan"
			],
			[
				"product_name" => "PLN 50.000",
				"category" => "PLN",
				"brand" => "PLN",
				"type" => "Umum",
				"seller_name" => "BC***",
				"price" => 50599,
				"buyer_sku_code" => "pln50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "masukkan nomor meter/id pelanggan"
			],
			[
				"product_name" => "Telkomsel 10.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "NE***",
				"price" => 10075,
				"buyer_sku_code" => "s10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 100.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "MC***",
				"price" => 97325,
				"buyer_sku_code" => "s100",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 15.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "DY***",
				"price" => 14879,
				"buyer_sku_code" => "s15",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 20.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "AL***",
				"price" => 21670,
				"buyer_sku_code" => "s20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:5",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 25.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "PT***",
				"price" => 24715,
				"buyer_sku_code" => "s25",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "22:30",
				"end_cut_off" =>"23:20",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 30.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "AG***",
				"price" => 29875,
				"buyer_sku_code" => "s30",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:10",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 5.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "SM***",
				"price" => 5205,
				"buyer_sku_code" => "s5",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:50",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Telkomsel 50.000",
				"category" => "Pulsa",
				"brand" => "TELKOMSEL",
				"type" => "Umum",
				"seller_name" => "AM***",
				"price" => 49225,
				"buyer_sku_code" => "s50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "SHOPEE PAY 100.000",
				"category" => "E-Money",
				"brand" => "SHOPEE PAY",
				"type" => "Umum",
				"seller_name" => "MU***",
				"price" => 100200,
				"buyer_sku_code" => "shopee100",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "SHOPEE PAY 100.000"
			],
			[
				"product_name" => "SHOPEE PAY 50.000",
				"category" => "E-Money",
				"brand" => "SHOPEE PAY",
				"type" => "Umum",
				"seller_name" => "Me***",
				"price" => 50300,
				"buyer_sku_code" => "shopee50",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "SHOPEE PAY 50.000"
			],
			[
				"product_name" => "Smartfren 10.000",
				"category" => "Pulsa",
				"brand" => "SMARTFREN",
				"type" => "Umum",
				"seller_name" => "Na***",
				"price" => 9915,
				"buyer_sku_code" => "sm10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Reguler"
			],
			[
				"product_name" => "Smartfren Data Unlimited Harian 1 GB Berlaku 7 Hari",
				"category" => "Data",
				"brand" => "SMARTFREN",
				"type" => "Unlimited",
				"seller_name" => "Om***",
				"price" => 21840,
				"buyer_sku_code" => "smdu1",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Batas pemakaian wajar 1GB/hari, Unlimited 24 Jam, Gratis Nelpon ke sesama smartfren, Berlaku 7 hari"
			],
			[
				"product_name" => "Smartfren Data Unlimited Harian 2 GB Berlaku 28 Hari",
				"category" => "Data",
				"brand" => "SMARTFREN",
				"type" => "Unlimited",
				"seller_name" => "De***",
				"price" => 91425,
				"buyer_sku_code" => "smdu2",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:59",
				"end_cut_off" =>"0:1",
				"description" => "Batas pemakaian wajar 2GB/hari, Unlimited 24 Jam, Gratis Nelpon ke sesama smartfren, Berlaku 28 hari"
			],
			[
				"product_name" => "Three 10.000",
				"category" => "Pulsa",
				"brand" => "TRI",
				"type" => "Umum",
				"seller_name" => "MU***",
				"price" => 10055,
				"buyer_sku_code" => "t10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:20",
				"description" => "Reguler"
			],
			[
				"product_name" => "Three 20.000",
				"category" => "Pulsa",
				"brand" => "TRI",
				"type" => "Umum",
				"seller_name" => "CV***",
				"price" => 19552,
				"buyer_sku_code" => "t20",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Three 5.000",
				"category" => "Pulsa",
				"brand" => "TRI",
				"type" => "Umum",
				"seller_name" => "AM***",
				"price" => 6548,
				"buyer_sku_code" => "t5",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Aktivasi Perdana Tri Happy S+ 30 Hari",
				"category" => "Aktivasi Perdana",
				"brand" => "TRI",
				"type" => "Happy",
				"seller_name" => "Jo***",
				"price" => 13035,
				"buyer_sku_code" => "tacthappys",
				"buyer_product_status" => true,
				"seller_product_status" =>false,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "22:0",
				"end_cut_off" =>"6:15",
				"description" => "Aktivasi Perdana Tri Happy S+ 30 Hari"
			],
			[
				"product_name" => "Tri Tambah Masa Aktif Kartu  4 Bulan",
				"category" => "Masa Aktif",
				"brand" => "TRI",
				"type" => "Umum",
				"seller_name" => "Om***",
				"price" => 3000,
				"buyer_sku_code" => "tactive4m",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Hanya menambah masa aktif kartu 4 bulan, bisa akumulasi"
			],
			[
				"product_name" => "Aktivasi Voucher Axis 1 GB 1 Hari",
				"category" => "Aktivasi Voucher",
				"brand" => "AXIS",
				"type" => "Aigo",
				"seller_name" => "Ki***",
				"price" => 5620,
				"buyer_sku_code" => "vax1",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => false,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:30",
				"description" => "AIGO Mini Bronet 24Jam 1GB + Kuota di Kota-mu 1hr"
			],
			[
				"product_name" => "Aktivasi Voucher Axis 3 GB 3 Hari",
				"category" => "Aktivasi Voucher",
				"brand" => "AXIS",
				"type" => "Aigo",
				"seller_name" => "Fl***",
				"price" => 10322,
				"buyer_sku_code" => "vax2",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => false,
				"start_cut_off" => "23:30",
				"end_cut_off" =>"0:15",
				"description" => "AIGO Mini 3GB + Kuota di Kota-mu 3hr"
			],
			[
				"product_name" => "Aktivasi Voucher XL Xtra Combo Flex S 28 Hari",
				"category" => "Aktivasi Voucher",
				"brand" => "XL",
				"type" => "Xtra Combo Flex",
				"seller_name" => "CV***",
				"price" => 28610,
				"buyer_sku_code" => "vflexs",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:15",
				"description" => "Xtra Combo Flex S"
			],
			[
				"product_name" => "Voucher Telkomsel 2.5 GB 5 Hari (Jawa Barat)",
				"category" => "Voucher",
				"brand" => "TELKOMSEL",
				"type" => "Jawa Barat",
				"seller_name" => "SP***",
				"price" => 11599,
				"buyer_sku_code" => "vs2g5d",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Voucher paket Internet 1 GB & 1.5 GB Lokal Internet Jawa berlaku selama 5 Hari"
			],
			[
				"product_name" => "Xl 10.000",
				"category" => "Pulsa",
				"brand" => "XL",
				"type" => "Umum",
				"seller_name" => "Om***",
				"price" => 10844,
				"buyer_sku_code" => "x10",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:45",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Xl 5.000",
				"category" => "Pulsa",
				"brand" => "XL",
				"type" => "Umum",
				"seller_name" => "CV***",
				"price" => 5844,
				"buyer_sku_code" => "x5",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "23:40",
				"end_cut_off" =>"0:15",
				"description" => "Reguler"
			],
			[
				"product_name" => "Indosat Yellow 1 GB 1 Hari",
				"category" => "Data",
				"brand" => "INDOSAT",
				"type" => "Yellow",
				"seller_name" => "Lu***",
				"price" => 6005,
				"buyer_sku_code" => "yellow1",
				"buyer_product_status" => true,
				"seller_product_status" =>true,
				"unlimited_stock" => true,
				"stock" =>0,
				"multi" => true,
				"start_cut_off" => "0:0",
				"end_cut_off" =>"0:0",
				"description" => "Online Gaspol 1GB 1 Hari"
			]
		]);
	}
}
