services:
  cloud-store:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: store-prod:latest
    container_name: cloud-store-prod
    ports:
      - "8000:80"
    environment:
      - TYPE=WEB
      - APP_KEY=${APP_KEY}
      - DIGIFLAZZ_SECRET_KEY=${DIGIFLAZZ_SECRET_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - APP_NAME="Cloud Store"
      - APP_ENV=production
      - APP_DEBUG="false"
      - APP_TIMEZONE="UTC"
      - APP_URL=https://store.idcloudnest.com
      - APP_LOCALE=id
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=daily
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - REDIS_CLIENT=predis
      - REDIS_HOST=core-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - MIDTRANS_IS_PRODUCTION=${MIDTRANS_IS_PRODUCTION}
      - MIDTRANS_IS_SANITIZED=true
      - MIDTRANS_IS_3DS=true
      - UID=1002
      - GID=1003
      - DIGIFLAZZ_MODE=production
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=80
    networks:
      - core

  cloud-store-queue:
    image: store-prod:latest
    container_name: cloud-store-queue-prod
    environment:
      - TYPE=QUEUE
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: php artisan queue:work --queue=transactions,default --tries=3 --timeout=90
    networks:
      - core

networks:
  core:
    external: true
