services:
  cloud-store-dev:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
      dockerfile: Dockerfile.dev
    image: store-dev:latest
    container_name: cloud-store-dev
    environment:
      - TYPE=WEB
    ports:
      - "8001:80"
    volumes:
      - .:/app
      - ~/.ssh/dwialim.pem:/app/dwialim.pem:ro
    env_file:
      - .env
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=80
    networks:
      - core

  cloud-store-queue-dev:
    image: store-dev:latest
    container_name: cloud-store-queue-dev
    # command: php artisan queue:work --tries=3 --timeout=90
    environment:
      - TYPE=QUEUE
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: php artisan queue:work --queue=transactions,logging,default --tries=3 --timeout=30
    networks:
      - core

  cloud-store-scheduler-dev:
    image: store-dev:latest
    container_name: cloud-store-scheduler-dev
    environment:
      - TYPE=SCHEDULER
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: php artisan schedule:work
    networks:
      - core

  cloud-store-sawit-db-dev:
    image: store-dev:latest
    container_name: cloud-store-sawit-db-dev
    environment:
      - TYPE=DB_SAWIT
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: php sawitdb/bin/sawit-server.php
    networks:
      - core

networks:
  core:
    external: true
