FROM php:8.2-cli

ARG UID=1000
ARG GID=1000

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install \
    pdo_mysql \
    mbstring \
    bcmath \
    gd \
    zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Create user with UID 1000
RUN useradd -u ${UID} -m dwi

# Copy source code
COPY . /app

RUN chown -R ${UID}:${GID} /app

# Entrypoint
RUN chmod +x /app/entrypoint.sh

USER ${UID}

# RUN composer install

ENTRYPOINT ["/app/entrypoint.sh"]

# Run Laravel built-in server
# CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]
