services:
  cloud-store-dev:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
      dockerfile: Dockerfile.dev
    image: store-dev:latest
    container_name: cloud-store-dev
    ports:
      - "8001:80"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    networks:
      - core

networks:
  core:
    external: true
