services:
  cloud-store:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: store:latest
    container_name: cloud-store
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
    networks:
      - core

networks:
  core:
    external: true
