services:
  cloud-store:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: store-prod:latest
    container_name: cloud-store
    ports:
      - "8000:80"
    environment:
      - APP_KEY=${APP_KEY}
      - DIGIFLAZZ_SECRET_KEY=${DIGIFLAZZ_SECRET_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME="Cloud Store"
      - APP_ENV=production
      - APP_DEBUG="false"
      - APP_TIMEZONE="UTC"
      - APP_URL=http://localhost
      - APP_LOCALE=id
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=daily
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - MIDTRANS_IS_PRODUCTION=${MIDTRANS_IS_PRODUCTION}
      - MIDTRANS_IS_SANITIZED=true
      - MIDTRANS_IS_3DS=true
    restart: always
    networks:
      - core

networks:
  core:
    external: true
