name: Auto Deploy (Self-Hosted)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          whoami
          id
          hostname
          pwd

      # - name: Docker info
      #   run: |
      #     docker --version
      #     docker compose version

      # - name: Stop existing containers
      #   run: |
      #     docker compose -f docker-compose.prod.yml down

      - name: Build & Deploy (Docker Compose)
        run: |
          export APP_KEY="${{ secrets.APP_KEY }}"
          export DIGIFLAZZ_SECRET_KEY="${{ secrets.DIGIFLAZZ_SECRET_KEY }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_USERNAME="${{ secrets.DB_USERNAME }}"
          export DB_CONNECTION="${{ vars.DB_CONNECTION }}"
          export DB_DATABASE="${{ vars.DB_DATABASE }}"
          export DB_HOST="${{ vars.DB_HOST }}"
          export DB_PORT="${{ vars.DB_PORT }}"
          export MIDTRANS_CLIENT_KEY="${{ secrets.MIDTRANS_CLIENT_KEY }}"
          export MIDTRANS_IS_PRODUCTION="${{ secrets.MIDTRANS_IS_PRODUCTION }}"
          export MIDTRANS_SERVER_KEY="${{ secrets.MIDTRANS_SERVER_KEY }}"
          export FIREBASE_CREDENTIALS="${{ secrets.FIREBASE_CREDENTIALS }}"
          export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"

          docker compose -f docker-compose.prod.yml up -d --build

      - name: Cleanup unused images
        run: |
          docker image prune -f
